name: Resume

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: build latest
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Login to Docker hub
      run: docker login -u ${{secrete.REGISTRY_USERNAME}} -p ${{secrete.REGISTRY_PASSWORD}}
    - name: Tag image
      run: docker tag my-image-name:${{github.run_number}} ${{secrete.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}
    - name: docker push
      run: docker push ${{secrete.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}